### ISSUE TITLE
SKServer failing carthage build in Xcode 11.7

### ISSUE THREAD

**Issue by yamataku29** [pvzig/SlackKit#187]
When I try to include SlackKit via Carthage, I get the following error on carthage update. My Cartfile only contains github "SlackKit/SlackKit" as documented.

```
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/yamataku/.ghq/github.com/init-inc/EntranceApp-iOS/Carthage/Checkouts/SlackKit/SlackKit.xcodeproj -scheme SKServer -configuration Release -derivedDataPath /Users/yamataku/Library/Caches/org.carthage.CarthageKit/DerivedData/11.7_11E801a/SlackKit/4.5.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/v_/9cnk0gwx7nv45kmmkrdmrkvr0000gn/T/SlackKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/yamataku/.ghq/github.com/init-inc/EntranceApp-iOS/Carthage/Checkouts/SlackKit)
```

The build log contains these errors:

```
/Carthage/Checkouts/SlackKit/SKServer/Sources/Conformers/SwifterServer.swift:25:8: error: failed to load module 'Swifter'
import Swifter
       ^

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwift normal armv7
(4 failures)
```

**Comment by pvzig** [comment]
Sorry for the delayed response - this should be resolved by [4.6.0](https://github.com/pvzig/SlackKit/releases/tag/4.6.0). Let me know if you're still seeing issues.
